version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/simar437/spinnaker"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "shell"